apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa1
commonLabels:
  common: prueba-cd-argo
patchesStrategicMerge:
- deployment_patch.yaml
resources:
- ../../base
images:
- name: caperiver/prueba
  newName: caperiver/prueba
  newTag: "3"
