apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: desa
commonLabels:
  common: prueba-cd
bases:
- ../../base
patchesStrategicMerge:
- deployment_patch.yaml
patches:
- path: ingress_patch.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: ingress-app1

